creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    kms: arn:aws:kms:ap-southeast-1:290913681714:key/e6b5bb9c-b073-4b54-8b3e-3c6d1752e543
  - path_regex: .*.env
    kms: arn:aws:kms:ap-southeast-1:290913681714:key/e6b5bb9c-b073-4b54-8b3e-3c6d1752e543
